stages:
  - deploy

deploy:
  stage: deploy
  image: python:3.7.3-stretch
  script:
    - pip install twine
    - python setup.py sdist bdist_wheel
    - twine upload --repository nexus dist/*
  only:
    - master
