stages:
  - deploy

deploy:
  stage: deploy
  image: python:3.9.1-slim-buster
  script:
    - apt-get update
    - apt-get install -y git
    - pip install poetry
    - pip install poetry-dynamic-versioning
    - sed -i "s|\${NEXUS_URL}|$NEXUS_URL|g; s|\${NEXUS_HOST}|$NEXUS_HOST|g;" pyproject.toml
    - poetry build
    - poetry publish -r ostadkar_publish -u $NEXUS_USER -p $NEXUS_PASS
  only:
    - tags
  tags:
    - develop