stages:
  - deploy

deploy:
  stage: deploy
  image: python:3.7-stretch
  script:
    - python3.7 setup.py sdist bdist_wheel
    - twine upload --repository-url ${NEXUS_HOST}/repository/pypi-internal/ --username ${NEXUS_USER} --password ${NEXUS_PASS} dist/*
  only:
    - master
