stages:
  - deploy

deploy:
  stage: deploy
  image: python:3.9.1-slim-buster
  script:
    - apt-get update
    - apt-get install -y git
    - pip install poetry
    - pip install poetry-dynamic-versioning
    - poetry build
    - poetry publish --r https://nexus.ostadkar.pro/repository/pypi-internal/ -u gitlab -p "Dsed+4P0sT6WZfzt6gwriQ=="
  only:
    - tags
  tags:
    - develop